#### `Notebook Number:-3`
#### we are creating new features here which can help in our ML part

In [22]:
# Just adding the importent library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
#loding the dataset
df = pd.read_csv(r"P:\Mini_Project\Datasets\Transaction_risk_insights_cleaned.csv")
df["transaction_date"] = pd.to_datetime(df["transaction_date"])
df.sample(10)

,transaction_id,customer_id,transaction_date,transaction_time,account_type,transaction_type,transaction_amount,transaction_direction,account_balance,merchant_category,state,credit_score,has_loan,loan_type,emi_amount,transaction_status,channel,kyc_status,is_fraud,transaction_hour
266056,TXN000266057,CUST072274,2021-06-03,1900-01-01 12:54:00,Current,IMPS,46558.15,Debit,26578.04,E-Commerce,Maharashtra,376,1,Personal,1489.99,Failed,Web,Verified,0,12
342686,TXN000342687,CUST076325,2022-02-12,1900-01-01 03:30:00,NRI,Auto_Debit,1712.56,Debit,24643.39,Peer Transfer,West Bengal,311,1,Auto,15992.53,Success,Branch,Verified,0,3
200728,TXN000200729,CUST013334,2020-10-29,1900-01-01 14:22:00,NRI,UPI,575.31,Credit,81372.34,Travel,Maharashtra,830,0,No Loan,0.00,Success,ATM,Pending,0,14
467378,TXN000467379,CUST010208,2023-04-02,1900-01-01 13:31:00,Current,UPI,117.29,Debit,10149.90,Retail,Karnataka,597,0,No Loan,0.00,Success,Mobile_App,Pending,0,13
219534,TXN000219535,CUST035108,2020-12-30,1900-01-01 14:14:00,Salary,Net_Banking,11640.12,Debit,49761.07,Retail,Rajasthan,835,0,No Loan,0.00,Success,Web,Verified,0,14
469396,TXN000469397,CUST058369,2023-04-09,1900-01-01 08:32:00,Fixed Deposit,IMPS,862.49,Credit,19049.69,Real Estate,Maharashtra,547,1,Home,6715.93,Success,ATM,Verified,0,8
267219,TXN000267220,CUST041725,2021-06-07,1900-01-01 01:46:00,Savings,NEFT,76.90,Credit,24629.38,Retail,Karnataka,436,0,No Loan,0.00,Success,Mobile_App,Verified,0,1
323826,TXN000323827,CUST063001,2021-12-12,1900-01-01 15:50:00,Salary,NEFT,9192.11,Credit,32645.92,Government,Punjab,851,1,Home,1575.19,Reversed,Web,Verified,0,15
35363,TXN000035364,CUST000740,2019-04-29,1900-01-01 12:58:00,Savings,IMPS,3525.06,Debit,36386.28,E-Commerce,Maharashtra,781,0,No Loan,0.00,Success,POS_Terminal,Verified,0,12
266427,TXN000266428,CUST007733,2021-06-04,1900-01-01 21:24:00,Salary,Net_Banking,1818.82,Debit,39484.49,E-Commerce,Delhi,324,1,Home,1018.41,Success,ATM,Verified,0,21

#### `1:-` First we extract useful information from the transaction_date column.

In [24]:
# now we will extract year
df["transaction_year"] = df["transaction_date"].dt.year

# now we will extract month
df["transaction_month"] = df["transaction_date"].dt.month

# now we will extract day
df["transaction_day"] = df["transaction_date"].dt.day

# now we will extract day name
df["day_of_week"] = df["transaction_date"].dt.day_name()

# now we will identify weekend transactions
df["is_weekend"] = (
    df["transaction_date"].dt.dayofweek >= 5
).astype(int)

In [25]:
# now we will see newly created features
df[[
    "transaction_date",
    "transaction_year",
    "transaction_month",
    "transaction_day",
    "day_of_week",
    "is_weekend"
]].sample(10)

,transaction_date,transaction_year,transaction_month,transaction_day,day_of_week,is_weekend
211744,2020-12-04,2020,12,4,Friday,0
434172,2022-12-11,2022,12,11,Sunday,1
10820,2019-02-06,2019,2,6,Wednesday,0
285131,2021-08-06,2021,8,6,Friday,0
349687,2022-03-08,2022,3,8,Tuesday,0
57195,2019-07-10,2019,7,10,Wednesday,0
113132,2020-01-11,2020,1,11,Saturday,1
75369,2019-09-07,2019,9,7,Saturday,1
282515,2021-07-28,2021,7,28,Wednesday,0
376352,2022-06-04,2022,6,4,Saturday,1

#### `2:-` Now we will  do transaction time period categorization
- We already have a transaction_hour column. We'll use it to divide transactions into four time periods.

In [26]:
# Defining the time periods
conditions = [
    (df["transaction_hour"] >= 0) & (df["transaction_hour"] < 6),
    (df["transaction_hour"] >= 6) & (df["transaction_hour"] < 12),
    (df["transaction_hour"] >= 12) & (df["transaction_hour"] < 18),
    (df["transaction_hour"] >= 18) & (df["transaction_hour"] <= 23)
]

periods = ["Night", "Morning", "Afternoon", "Evening"]

# Creating the the new feature
df["time_period"] = np.select(conditions, periods, default="Unknown")

In [27]:
# Now we are checking the newly created feature
df[["transaction_hour", "time_period"]].sample(10)

        transaction_hour time_period
444752                14   Afternoon
5758                  15   Afternoon
506888                18     Evening
345160                11     Morning
164483                10     Morning
170197                13   Afternoon
168396                22     Evening
60437                  8     Morning
367365                14   Afternoon
275926                 6     Morning

#### `3:-` Now we will do transaction Amount Categorization

In [28]:
# Now we will make three catagories based on transaction amount like low, medium and high
conditions = [
    df["transaction_amount"] < 10000,
    (df["transaction_amount"] >= 10000) &
    (df["transaction_amount"] <= 50000),
    df["transaction_amount"] > 50000
]

categories = ["Low", "Medium", "High"]

df["transaction_amount_category"] = np.select(
    conditions,
    categories,
    default="Unknown"
)

In [29]:
# Now we will see the newly created feature
df[["transaction_amount","transaction_amount_category"]].head(10)

   transaction_amount transaction_amount_category
0             1820.17                         Low
1              392.67                         Low
2             1255.97                         Low
3             2580.68                         Low
4             2573.80                         Low
5            39172.48                      Medium
6             4008.09                         Low
7            17797.85                      Medium
8             3284.62                         Low
9              921.64                         Low

In [30]:
df["transaction_amount_category"].value_counts()

transaction_amount_category
Low       422188
Medium     71979
High       55833
Name: count, dtype: int64

In [31]:
# now we will calculate the percentage of each category in transaction_amount_category
(df["transaction_amount_category"].value_counts(normalize=True) * 100).round(2)

transaction_amount_category
Low       76.76
Medium    13.09
High      10.15
Name: proportion, dtype: float64

#### `4:-` Now we will do the Account Balance Categorization

In [32]:
# We will categorize account balances into three groups.
conditions = [
    df["account_balance"] <= 25000,
    (df["account_balance"] > 25000) &
    (df["account_balance"] <= 100000),
    df["account_balance"] > 100000
]

categories = ["Low", "Medium", "High"]

df["balance_category"] = np.select(
    conditions,
    categories,
    default="Unknown"
)

In [33]:
df[["account_balance", "balance_category"]].head(10)

   account_balance balance_category
0        609365.31             High
1         14451.14              Low
2         47621.87           Medium
3         34467.85           Medium
4         26617.40           Medium
5          1798.86              Low
6        177668.37             High
7         17568.23              Low
8         66973.00           Medium
9         36054.94           Medium

In [34]:
# now we will verify the balance category distribution
df["balance_category"].value_counts()
# now we will calculate the percentage of each category in balance_category
(df["balance_category"].value_counts(normalize=True) * 100).round(2)

balance_category
Medium    39.48
Low       38.65
High      21.87
Name: proportion, dtype: float64

#### `5:-` Now we will do credit Score Categorization

In [35]:
# Now we will categorize credit scores into three groups.
conditions = [
    (df["credit_score"] >= 300) & (df["credit_score"] <= 499),
    (df["credit_score"] >= 500) & (df["credit_score"] <= 699),
    (df["credit_score"] >= 700) & (df["credit_score"] <= 899)
]

categories = ["Low", "Medium", "High"]

df["credit_score_category"] = np.select(
    conditions,
    categories,
    default="Unknown"
)

In [36]:
df[["credit_score", "credit_score_category"]].sample(10)

        credit_score credit_score_category
115515           653                Medium
297561           600                Medium
53011            702                  High
473468           339                   Low
16081            857                  High
224659           514                Medium
227059           772                  High
97102            579                Medium
501082           594                Medium
191642           537                Medium

In [37]:
# Now we will verify the category distribution
df["credit_score_category"].value_counts()

credit_score_category
Medium    183989
High      183212
Low       182799
Name: count, dtype: int64

In [38]:
# now we will calculate Category percentages
(df["credit_score_category"].value_counts(normalize=True) * 100).round(2)

credit_score_category
Medium    33.45
High      33.31
Low       33.24
Name: proportion, dtype: float64

#### `6:-` Now we will make transaction frequency Feature

In [39]:
# This feature will calculate how many transactions each customer has made in the dataset.

# Count the total transactions made by each customer
df["customer_transaction_count"] =(
    df.groupby("customer_id")["transaction_id"]
    .transform("count")
)

In [40]:
df[["customer_id","transaction_id","customer_transaction_count"]].sample(10)

       customer_id transaction_id  customer_transaction_count
370407  CUST002105   TXN000370408                           7
371928  CUST027249   TXN000371929                           7
205843  CUST046212   TXN000205844                           5
192705  CUST016150   TXN000192706                           7
143519  CUST065808   TXN000143520                           8
466255  CUST057252   TXN000466256                           8
200471  CUST015069   TXN000200472                           7
26506   CUST079670   TXN000026507                           6
326649  CUST026769   TXN000326650                           5
19930   CUST013342   TXN000019931                           6

In [41]:
# lets check whether we have created all our intended features or not.
df.columns.tolist()

['transaction_id',
 'customer_id',
 'transaction_date',
 'transaction_time',
 'account_type',
 'transaction_type',
 'transaction_amount',
 'transaction_direction',
 'account_balance',
 'merchant_category',
 'state',
 'credit_score',
 'has_loan',
 'loan_type',
 'emi_amount',
 'transaction_status',
 'channel',
 'kyc_status',
 'is_fraud',
 'transaction_hour',
 'transaction_year',
 'transaction_month',
 'transaction_day',
 'day_of_week',
 'is_weekend',
 'time_period',
 'transaction_amount_category',
 'balance_category',
 'credit_score_category',
 'customer_transaction_count']

#### Now we will save all our new features in a new dataset

In [42]:
df.to_csv("../Datasets/Transaction_risk_insights_feature_engineered.csv",index=False)