#### `Notebook Number:-3`
#### we are creating new features here which can help in our ML part

In [1]:
# Just adding the importent library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
#loding the dataset
df = pd.read_csv(r"P:\Mini_Project\Datasets\Transaction_risk_insights_cleaned.csv")
df["transaction_date"] = pd.to_datetime(df["transaction_date"])
df.sample(10)

,transaction_id,customer_id,transaction_date,transaction_time,account_type,transaction_type,transaction_amount,transaction_direction,account_balance,merchant_category,state,credit_score,has_loan,loan_type,emi_amount,transaction_status,channel,kyc_status,is_fraud,transaction_hour
124941,TXN000124942,CUST078966,2020-02-19,1900-01-01 04:57:00,NRI,UPI,351.67,Debit,12681.13,Utilities,Delhi,822,1,Education,3799.08,Failed,Mobile_App,Verified,0,4
226389,TXN000226390,CUST016374,2021-01-22,1900-01-01 19:20:00,Current,Credit_Card,8645.92,Debit,6919.46,E-Commerce,Punjab,335,0,No Loan,0.00,Success,Mobile_App,Verified,0,19
14897,TXN000014898,CUST015578,2019-02-19,1900-01-01 13:56:00,Savings,ATM_Withdrawal,2000.00,Debit,37435.32,Retail,Rajasthan,850,0,No Loan,0.00,Success,ATM,Verified,0,13
190349,TXN000190350,CUST028549,2020-09-23,1900-01-01 08:13:00,NRI,UPI,1098.55,Credit,12991.33,Healthcare,Tamil Nadu,358,1,Loan Type Unknown,21503.95,Success,ATM,Verified,0,8
429118,TXN000429119,CUST056184,2022-11-25,1900-01-01 05:32:00,Salary,Net_Banking,18201.06,Credit,8232.96,Peer Transfer,Gujarat,409,0,No Loan,0.00,Success,ATM,Verified,0,5
155235,TXN000155236,CUST017301,2020-05-30,1900-01-01 08:01:00,Current,UPI,2185.75,Credit,48451.53,E-Commerce,Karnataka,567,0,No Loan,0.00,Success,Mobile_App,Expired,0,8
523018,TXN000523019,CUST063394,2023-10-03,1900-01-01 11:14:00,Fixed Deposit,IMPS,891.33,Debit,62240.52,Food & Dining,UP,648,0,No Loan,0.00,Success,Branch,Pending,0,11
157631,TXN000157632,CUST052757,2020-06-07,1900-01-01 19:45:00,Current,ATM_Withdrawal,1000.00,Debit,20610.05,Healthcare,Tamil Nadu,380,0,No Loan,0.00,Success,Mobile_App,Expired,0,19
36339,TXN000036340,CUST011383,2019-05-02,1900-01-01 10:25:00,Savings,NEFT,27678.24,Debit,12186.39,Food & Dining,Gujarat,322,1,Home,6981.09,Success,API,Verified,0,10
179831,TXN000179832,CUST040255,2020-08-20,1900-01-01 09:02:00,Current,NEFT,5676.71,Debit,81343.59,Travel,West Bengal,607,0,No Loan,0.00,Success,Mobile_App,Verified,0,9

#### `1` First we extract useful information from the transaction_date column.

In [5]:
# now we will extract year
df["transaction_year"] = df["transaction_date"].dt.year

# now we will extract month
df["transaction_month"] = df["transaction_date"].dt.month

# now we will extract day
df["transaction_day"] = df["transaction_date"].dt.day

# now we will extract day name
df["day_of_week"] = df["transaction_date"].dt.day_name()

# now we will identify weekend transactions
df["is_weekend"] = (
    df["transaction_date"].dt.dayofweek >= 5
).astype(int)

In [8]:
# now we will see newly created features
df[[
    "transaction_date",
    "transaction_year",
    "transaction_month",
    "transaction_day",
    "day_of_week",
    "is_weekend"
]].sample(10)

,transaction_date,transaction_year,transaction_month,transaction_day,day_of_week,is_weekend
374322,2022-05-29,2022,5,29,Sunday,1
29054,2019-04-08,2019,4,8,Monday,0
542384,2023-12-07,2023,12,7,Thursday,0
491812,2023-06-22,2023,6,22,Thursday,0
217566,2020-12-24,2020,12,24,Thursday,0
122865,2020-02-12,2020,2,12,Wednesday,0
18697,2019-03-04,2019,3,4,Monday,0
245500,2021-03-27,2021,3,27,Saturday,1
161413,2020-06-20,2020,6,20,Saturday,1
37310,2019-05-05,2019,5,5,Sunday,1

#### `2`Now we will  do transaction time period categorization
- We already have a transaction_hour column. We'll use it to divide transactions into four time periods.

In [9]:
# Defining the time periods
conditions = [
    (df["transaction_hour"] >= 0) & (df["transaction_hour"] < 6),
    (df["transaction_hour"] >= 6) & (df["transaction_hour"] < 12),
    (df["transaction_hour"] >= 12) & (df["transaction_hour"] < 18),
    (df["transaction_hour"] >= 18) & (df["transaction_hour"] <= 23)
]

periods = ["Night", "Morning", "Afternoon", "Evening"]

# Creating the the new feature
df["time_period"] = np.select(conditions, periods, default="Unknown")

In [10]:
# Now we are checking the newly created feature
df[["transaction_hour", "time_period"]].sample(10)

        transaction_hour time_period
279583                11     Morning
233559                 5       Night
231821                 8     Morning
545179                 2       Night
355772                13   Afternoon
168204                18     Evening
378751                 5       Night
227602                16   Afternoon
185292                10     Morning
301280                 0       Night

#### `3` Now we will do transaction Amount Categorization

In [12]:
# Now we will make three catagories based on transaction amount like low, medium and high
conditions = [
    df["transaction_amount"] < 10000,
    (df["transaction_amount"] >= 10000) &
    (df["transaction_amount"] <= 50000),
    df["transaction_amount"] > 50000
]

categories = ["Low", "Medium", "High"]

df["transaction_amount_category"] = np.select(
    conditions,
    categories,
    default="Unknown"
)

In [13]:
# Now we will see the newly created feature
df[["transaction_amount","transaction_amount_category"]].head(10)

   transaction_amount transaction_amount_category
0             1820.17                         Low
1              392.67                         Low
2             1255.97                         Low
3             2580.68                         Low
4             2573.80                         Low
5            39172.48                      Medium
6             4008.09                         Low
7            17797.85                      Medium
8             3284.62                         Low
9              921.64                         Low

In [14]:
df["transaction_amount_category"].value_counts()

transaction_amount_category
Low       422188
Medium     71979
High       55833
Name: count, dtype: int64

In [16]:
# now we will calculate the percentage of each category in transaction_amount_category
(df["transaction_amount_category"].value_counts(normalize=True) * 100).round(2)

transaction_amount_category
Low       76.76
Medium    13.09
High      10.15
Name: proportion, dtype: float64

#### `4` Now we will do the Account Balance Categorization

In [19]:
# We will categorize account balances into three groups.
conditions = [
    df["account_balance"] <= 25000,
    (df["account_balance"] > 25000) &
    (df["account_balance"] <= 100000),
    df["account_balance"] > 100000
]

categories = ["Low", "Medium", "High"]

df["balance_category"] = np.select(
    conditions,
    categories,
    default="Unknown"
)

In [18]:
df[["account_balance", "balance_category"]].head(10)

   account_balance balance_category
0        609365.31             High
1         14451.14              Low
2         47621.87           Medium
3         34467.85           Medium
4         26617.40           Medium
5          1798.86              Low
6        177668.37             High
7         17568.23              Low
8         66973.00           Medium
9         36054.94           Medium

In [20]:
# now we will verify the balance category distribution
df["balance_category"].value_counts()
# now we will calculate the percentage of each category in balance_category
(df["balance_category"].value_counts(normalize=True) * 100).round(2)

balance_category
Medium    39.48
Low       38.65
High      21.87
Name: proportion, dtype: float64

#### `5` Now we will do credit Score Categorization

In [23]:
# Now we will categorize credit scores into three groups.
conditions = [
    (df["credit_score"] >= 300) & (df["credit_score"] <= 499),
    (df["credit_score"] >= 500) & (df["credit_score"] <= 699),
    (df["credit_score"] >= 700) & (df["credit_score"] <= 899)
]

categories = ["Low", "Medium", "High"]

df["credit_score_category"] = np.select(
    conditions,
    categories,
    default="Unknown"
)

In [25]:
df[["credit_score", "credit_score_category"]].sample(10)

        credit_score credit_score_category
459679           500                Medium
152387           501                Medium
426795           568                Medium
489018           662                Medium
444303           597                Medium
489117           820                  High
542458           526                Medium
179870           702                  High
407685           439                   Low
17886            539                Medium

In [27]:
# Now we will verify the category distribution
df["credit_score_category"].value_counts()

credit_score_category
Medium    183989
High      183212
Low       182799
Name: count, dtype: int64

In [28]:
# now we will calculate Category percentages
(df["credit_score_category"].value_counts(normalize=True) * 100).round(2)

credit_score_category
Medium    33.45
High      33.31
Low       33.24
Name: proportion, dtype: float64

#### `6`Now we will make transaction frequency Feature

In [ ]:
# This feature will calculate how many transactions each customer has made in the dataset.

# Count the total transactions made by each customer
df["customer_transaction_count"] =(
    df.groupby("customer_id")["transaction_id"]
    .transform("count")
)

In [32]:
df[["customer_id","transaction_id","customer_transaction_count"]].sample(10)

       customer_id transaction_id  customer_transaction_count
519654  CUST007844   TXN000519655                           7
426029  CUST012469   TXN000426030                           9
8390    CUST055674   TXN000008391                           9
334358  CUST073494   TXN000334359                           7
541437  CUST077522   TXN000541438                           7
470589  CUST044127   TXN000470590                           9
388496  CUST021843   TXN000388497                           7
278935  CUST058406   TXN000278936                          11
93163   CUST009818   TXN000093164                           4
301303  CUST035684   TXN000301304                           3

In [34]:
# lets check whether we have created all our intended features or not.
df.columns.tolist()

['transaction_id',
 'customer_id',
 'transaction_date',
 'transaction_time',
 'account_type',
 'transaction_type',
 'transaction_amount',
 'transaction_direction',
 'account_balance',
 'merchant_category',
 'state',
 'credit_score',
 'has_loan',
 'loan_type',
 'emi_amount',
 'transaction_status',
 'channel',
 'kyc_status',
 'is_fraud',
 'transaction_hour',
 'transaction_year',
 'transaction_month',
 'transaction_day',
 'day_of_week',
 'is_weekend',
 'time_period',
 'transaction_amount_category',
 'balance_category',
 'credit_score_category',
 'customer_transaction_count']

#### Now we will save all our new features in a new dataset

In [37]:

df.to_csv(r"P:\Mini_Project\Datasets\Transaction_risk_insights_feature_engineered.csv",index=False)